[package]
name = "strukt-fs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
cap-fs-ext.workspace = true
cap-std.workspace = true
ignore.workspace = true
notify.workspace = true
serde.workspace = true
thiserror.workspace = true
trash.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
