[package]
name = "strukt-remote"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
blake3.workspace = true
cap-fs-ext.workspace = true
cap-std.workspace = true
ciborium.workspace = true
getrandom.workspace = true
serde.workspace = true
strukt-editor.workspace = true
strukt-fs.workspace = true
strukt-workspace.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true

[lints]
workspace = true
