[package]
name = "strukt-editor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
regex.workspace = true
ropey.workspace = true
serde.workspace = true
strukt-workspace.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
