[package]
name = "strukt-platform"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[target.'cfg(windows)'.dependencies]
cap-std.workspace = true
windows-sys = { version = "0.61.2", features = [
  "Win32_Foundation",
  "Win32_Storage_FileSystem",
] }

[target.'cfg(windows)'.dev-dependencies]
tempfile.workspace = true

[lints.clippy]
all = "deny"
pedantic = "deny"

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
